name: Maven Build (Java 17)
on:
  push:
    branches: ["**"]   # run on every branch push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'   # alternatives: zulu, corretto
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install
